# Generated by Django 4.2.6 on 2023-10-25 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kafka_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="genre",
            new_name="status",
        ),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="book",
            name="title",
        ),
        migrations.RemoveField(
            model_name="book",
            name="year",
        ),
    ]
