# Generated by Django 4.2.7 on 2023-11-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_app', '0002_rename_genre_book_status_remove_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='Katugasthota'),
        ),
    ]
