# Generated by Django 4.2.7 on 2023-12-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_app', '0008_book_current_book_freq_book_pow_book_voltage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='CURRENT',
            new_name='current',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='FREQ',
            new_name='freq',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='POW',
            new_name='pow',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='VOLTAGE',
            new_name='voltage',
        ),
    ]
