# Generated by Django 4.2.7 on 2023-12-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_app', '0009_rename_current_book_current_rename_freq_book_freq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='statusviewer',
            field=models.CharField(default='0'),
        ),
    ]
