# Generated by Django 4.2.7 on 2023-12-11 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_app', '0011_indications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indications',
        ),
    ]
