# Generated by Django 4.2.7 on 2023-12-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_app', '0012_delete_indications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_10000', models.CharField(max_length=20)),
                ('a_10001', models.CharField(max_length=20)),
                ('a_10002', models.CharField(max_length=20)),
                ('a_10003', models.CharField(max_length=20)),
                ('a_10004', models.CharField(max_length=20)),
                ('a_10005', models.CharField(max_length=20)),
                ('a_10006', models.CharField(max_length=20)),
                ('a_10007', models.CharField(max_length=20)),
                ('a_10008', models.CharField(max_length=20)),
                ('a_10009', models.CharField(max_length=20)),
                ('a_10010', models.CharField(max_length=20)),
                ('a_10011', models.CharField(max_length=20)),
                ('a_10000_time', models.CharField(max_length=20)),
                ('a_10001_time', models.CharField(max_length=20)),
                ('a_10002_time', models.CharField(max_length=20)),
                ('a_10003_time', models.CharField(max_length=20)),
                ('a_10004_time', models.CharField(max_length=20)),
                ('a_10005_time', models.CharField(max_length=20)),
                ('a_10006_time', models.CharField(max_length=20)),
                ('a_10007_time', models.CharField(max_length=20)),
                ('a_10008_time', models.CharField(max_length=20)),
                ('a_10009_time', models.CharField(max_length=20)),
                ('a_10010_time', models.CharField(max_length=20)),
                ('a_10011_time', models.CharField(max_length=20)),
            ],
        ),
    ]
