# Generated by Django 4.2.7 on 2023-12-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_app', '0015_singlepointindications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_5000', models.CharField(max_length=20)),
                ('a_5001', models.CharField(max_length=20)),
                ('a_5002', models.CharField(max_length=20)),
                ('a_5010', models.CharField(max_length=20)),
                ('a_5011', models.CharField(max_length=20)),
                ('a_5012', models.CharField(max_length=20)),
                ('a_5020', models.CharField(max_length=20)),
                ('a_5021', models.CharField(max_length=20)),
                ('a_5022', models.CharField(max_length=20)),
                ('a_5000_time', models.CharField(max_length=20)),
                ('a_5001_time', models.CharField(max_length=20)),
                ('a_5002_time', models.CharField(max_length=20)),
                ('a_5010_time', models.CharField(max_length=20)),
                ('a_5011_time', models.CharField(max_length=20)),
                ('a_5012_time', models.CharField(max_length=20)),
                ('a_5020_time', models.CharField(max_length=20)),
                ('a_5021_time', models.CharField(max_length=20)),
                ('a_5022_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DoublePointIndications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_8000', models.CharField(max_length=20)),
                ('a_8001', models.CharField(max_length=20)),
                ('a_8002', models.CharField(max_length=20)),
                ('a_8010', models.CharField(max_length=20)),
                ('a_8011', models.CharField(max_length=20)),
                ('a_8012', models.CharField(max_length=20)),
                ('a_8020', models.CharField(max_length=20)),
                ('a_8021', models.CharField(max_length=20)),
                ('a_8022', models.CharField(max_length=20)),
                ('a_8023', models.CharField(max_length=20)),
                ('a_8024', models.CharField(max_length=20)),
                ('a_8000_time', models.CharField(max_length=20)),
                ('a_8001_time', models.CharField(max_length=20)),
                ('a_8002_time', models.CharField(max_length=20)),
                ('a_8010_time', models.CharField(max_length=20)),
                ('a_8011_time', models.CharField(max_length=20)),
                ('a_8012_time', models.CharField(max_length=20)),
                ('a_8020_time', models.CharField(max_length=20)),
                ('a_8021_time', models.CharField(max_length=20)),
                ('a_8022_time', models.CharField(max_length=20)),
                ('a_8023_time', models.CharField(max_length=20)),
                ('a_8024_time', models.CharField(max_length=20)),
            ],
        ),
    ]
