# Generated by Django 4.2.7 on 2023-12-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_app', '0016_controls_doublepointindications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Controls',
        ),
        migrations.DeleteModel(
            name='DoublePointIndications',
        ),
        migrations.DeleteModel(
            name='SinglePointIndications',
        ),
    ]
