# Generated by Django 4.2.7 on 2023-12-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_app', '0018_controls_doublepointindication_singlepointindication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Controls',
        ),
        migrations.DeleteModel(
            name='DoublePointIndication',
        ),
        migrations.DeleteModel(
            name='SinglePointIndication',
        ),
    ]
