# Generated by Django 4.2.7 on 2023-12-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_app', '0020_controls_doublepointindication_singlepointindication'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlepointindication',
            name='type',
            field=models.CharField(default='0'),
        ),
    ]
