# Generated by Django 4.2.7 on 2023-12-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_app', '0022_remove_singlepointindication_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('timestamp', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ioa', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
    ]
