# Generated by Django 4.2.7 on 2023-12-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_app', '0023_measurements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurements',
        ),
    ]
