# Generated by Django 4.2.7 on 2023-12-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_app', '0029_singlepointindication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Controls',
        ),
        migrations.DeleteModel(
            name='DoublePointIndication',
        ),
    ]
