# Generated by Django 4.2.7 on 2023-12-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_app', '0034_alter_measurements_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controls',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doublepointindication',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='singlepointindication',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
